apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-5tea
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-dopj-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-5tea@sha256:ba7053bae54dbbae2504e1e466dafbd6d922f10c8d8de23258f82a2b7aac3c4b
        name: my-nodejs
        resources: {}
status: {}
